intro: |
  This page is a sample of the most common packages. To see a complete list see [the complete package list page](https://www.stackage.org/lts).

fundamentals-intro: |
  Core packages solve common problems and are regularly used in most Haskell programs.

fundamentals:
- name: base
  description: |
    Basic data types, file input/output, environment, concurrency, etc.
- name: text
  description: |
    Efficient immutable string/text data type for text/unicode data.
- name: time
  description: |
    Dealing with dates, times, time zones, milliseconds, durations, etc.
- name: filepath
  description: |
    Portably deal with file paths across Windows, OS X, Linux, etc.
- name: vector
  description: |
    Efficient arrays, immutable and mutable versions.
  page-url: https://raw.githubusercontent.com/commercialhaskell/haskelldocumentation/master/content/vector.md
- name: containers
  description: |
    Immutable maps/dictionaries, sets, and sequences with efficient appending.
- name: unordered-containers
  description: |
    Immutable maps/dictionaries and sets, implemented with hashes.
- name: directory
  description: |
    Portably deal with directories, files, file properties, etc.
- name: bytestring
  description: |
    Efficient immutable vectors of bytes for handling binary data.
- name: optparse-applicative
  description: |
    Utilities and combinators for parsing command line options
- name: criterion
  description: |
    Time how long (benchmark) your functions take to run with reliable statistical analysis.
- name: network
  description: |
    Network programming; TCP/UDP sockets, UNIX domain sockets, etc.
- name: process
  description: |
    Launch processes, one-shot or interactively, handle stdout, stderr, etc.
- name: async
  description: |
    Abstraction for performing many actions asynchronously and concurrently.
- name: aeson
  description: |
    Efficient JSON parsing and printing, automatic deriving for your data types, etc.
- name: attoparsec
  description: |
    Efficient parsing library, good for network protocols and complicated binary formats.
- name: QuickCheck
  description: |
    Check properties about functions with randomly generated inputs for sanity checks.
- name: stm
  description: |
    Software-transactional memory; for atomic, reliable, composable, concurrency.
- name: safe-exceptions
  description: |
    Extensible optionally-pure exceptions, abstracting over various types.
  page-url: https://raw.githubusercontent.com/fpco/safe-exceptions/master/README.md
- name: regex-compat
  description: |
    Simple POSIX-compatible regex matching.

commons-intro: |
    Packages for common tasks in Haskell programs. Typically more than one option.

commons:
- title: Testing
  slug: testing
  description: |
      Test frameworks that group together a bunch of tests and output
      success/fail results in a structured way.
  choices:
  - name: hspec
    description: |
      A testing framework inspired by the Ruby library RSpec,
      featuring a friendly language for defining tests.
  - name: tasty
    description: |
      A testing framework and library with a friendly API.

- title: Streaming
  slug: streaming
  description: |
      Libraries which provide constant-sized memory streaming to/from
      files, sockets, generated, etc.
  choices:
  - name: pipes
    description: |
      Combinators for awaiting and yielding, etc.
  - name: conduit
    description: |
      Combinators for awaiting and yielding, with leftovers, etc.
    page-url: https://raw.githubusercontent.com/commercialhaskell/haskelldocumentation/master/content/vector.md

- title: Web/HTTP requests
  slug: http-clients
  description: |
      Making HTTP requests to web servers, getting back a result,
      streaming, with various options about headers, redirections,
      etc.
  choices:
  - name: http-client
    description: |
      Simple HTTP client library with lots of options.
  - name: wreq
    description: |
      A wrapper over http-client with a lensy API.
